menu:
- {name: 'people', url: '/people'}
- {name: 'Research', url: '/publications'}
- {name: 'Teaching', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

Teaching:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/ghislainafavi'}
- {icon: 'twitter', link: 'https://twitter.com/GhislainAfavi'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/afavi-ghislain'}

contacts:
- {name: 'Ghislain Afavi ', title: 'Phd in economics', department: 'Economics', institution: 'University of Montreal', institution_address: '3150 Jean brillant', phone: '(514) 569-5551', email: 'ghislain.afavi@umontreal.ca', office: 'C-6070-1 Lionel Grioulx Building', image: 'assets/img/contact.jpg'}
